
package xmaze;

import graph.MazeGraph;
import java.awt.BorderLayout;
import javax.swing.JPanel;


/**
 * ΕΑΠ - ΠΛΗ31 - 4η ΕΡΓΑΣΙΑ 2015-2016
 * @author Tsakiridis Sotiris
 */
public class MazeGraphPanel extends javax.swing.JPanel {

    // panel size
    private final int width = 650;
    private final int height = 500;
    
    // Το γράφημα με τις κορυφές αρχής και τέλους
    private MazeGraph mazeGraph;

    
    /**
     * Creates new form graphPanel
     */
    public MazeGraphPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(600, 516));

        viewPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


   

    // Δημιουργία ενός νέου γράφου από ένα grid του maze
    public void setGraph(int[][] grid, boolean withDiagonals) {
        
        // Δημιουργούμε τον γράφο και παίρνουμε το default panel
        this.mazeGraph = new MazeGraph(grid, withDiagonals);
        JPanel panel = mazeGraph.getDefaultPanel();
         
        
        viewPanel.removeAll();
        viewPanel.repaint();
        viewPanel.revalidate();
        viewPanel.add(panel, BorderLayout.CENTER);
        viewPanel.repaint();
        viewPanel.revalidate();
      
        
        
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
